### PR TITLE
Add poplar tree

### PR DESCRIPTION
**Pull request by Rogier-5**
Poplars exist in two kinds: small and large trees. Both use the same
nodes, except for the sapling. Poplar leaves may drop one or the
other sapling.

Poplar trees require a humid environment, and water nearby. If those (relatively rare) conditions are satisfied, poplars can be abundant. Elsewhere, provided there is water nearby, an occasional poplar will spawn.

Poplar trees (large and small):
poplars

Some more:
poplars_2

Small and large poplar side-by-side:
poplar_large_small

Textures:
poplar_textures

### CODE REVIEW

**Comment by VanessaE** [comment]
Looks like this already needs a rebase.

**Comment by Rogier-5** [comment]
Rebased.

**Comment by Rogier-5** [comment]
I created a new screenshot as well, which I based on this branch (as it includes poplars as well). See pull request #27. So, if you like it, you can merge both poplars and the new screenshot at once by merging just the new-screenshot branch.

**Comment by 0-afflatus** [comment]
Very nice. My only reservation is that the leaves are slightly too light in colour, but that is easily fixed.

**Pull request merged**
