### PR TITLE
Adding date palm & improvement to coconut palm

### PR DESCRIPTION
**Pull request by Rogier-5**
I added a date palm, with some date-based food. Dates have separate male and female palms. As a special feature, after harvesting, dates regrow (but not too fast). Date regrowing  can be turned off.

I also changed the existing palm tree to regrow coconuts after harvesting. Obviously, it can also be turned off. If desired, the code converts exisiting coconut palms as well.

The first patch in this set adds a dependency on the vessels mod, as the drinking glass is used in the crafting recipes.

### CODE REVIEW

**Comment by sofar** [comment]
Care to post a few screenshots?

**Comment by Rogier-5** [comment]
I could have thought of that myself...

A group of date palms:
date_palms

Single tree (male)
date_palm_tree

Close-up of male and female tree with flowers and fruit in different stages of ripening
date_male_female_closeup

Textures
date_textures

Some coconut palms with coconuts in different stages of ripening.
coconuts_growing

**Comment by VanessaE** [comment]
I haven't tried the code, but I like how they look in the screenies.  :+1:

@Rogier-5 are you up to adding a couple more?  I've been wanting to add Italian cypress at least (seen at the top of this page, https://en.wikipedia.org/wiki/Cupressus_sempervirens), some kind of fruit tree (maybe cherry), just never got around to it.

**Comment by Rogier-5** [comment]
> I haven't tried the code, but I like how they look in the screenies

Thanks!

> are you up to adding a couple more?

I am currently thinking of adding poplar ([image 1](https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Populus_nigra-bekes.jpg/255px-Populus_nigra-bekes.jpg),[image 2](http://hovenierszaken.nl/wp-content/uploads/2015/10/Grotefoto-LHVXPCQJ-1024x732.jpg)), which shouldn't be too hard. Cypress and more fruit trees would be nice additions too, and I have been thinking of [prunus](http://cottagemagpie.com/img/k/kwanzan-flowering-cherry-prunus-serrulata.jpg), with seasonal effects...

I may add more (probably at least poplar), however there's so much more I also want to do (e.g. a major minetestmapper patchset that I am currently working on...), that I have to make choices about what to do when :-( So don't hold your breath.

**Pull request merged**
